# These are the links for funding and support for the SolanaGhostTrackerBot project
# Add links to your funding or support sites below

telegram: https://t.me/LikhonScripts
custom: ['www.likhonscripts.cloud']
